---
- name: Initial setup
  hosts: all
  gather_facts: false
  remote_user: gnus
  become: true
  tasks:
    - name: Add user slayed
      user:
        name: slayed
        shell: /bin/bash
    - name: Add slayed user to the sudoers
      copy:
        dest: "/etc/sudoers.d/slayed"
        content: "slayed  ALL=(ALL)  NOPASSWD: ALL"
    - name: Creates directory
      file:
        path: /home/slayed/.ssh
        state: directory
    - name: copy pub key to authorized_keys
      copy:
        src: "./.ssh/id_slayed.pub"
        dest: "/home/slayed/.ssh/authorized_keys"
    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes
    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
      notify:
        - restart ssh
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted