---
- name: Initial setup
  hosts: all
  gather_facts: false
  remote_user: slayed
  become: true
  tasks:
    - name: "Update apt-get repo and cache"
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: "Upgrade all apt packages"
      ansible.builtin.apt:
        upgrade: "dist"
        force_apt_get: true
