---
- name: Install essential packages
  hosts: all
  gather_facts: false
  remote_user: slayed
  become: true
  vars:
    user: "slayed"
  tasks:
    - name: "Update apt-get repo and cache"
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: "Install essential packages"
      ansible.builtin.apt:
        name:
          - tmux
          - docker-compose
          - htop
          - cockpit
          - cockpit-machines
          - neovim
          - vifm
          - network-manager
    - name: "Enable adn start docker.service"
      ansible.builtin.systemd:
        name: docker.service
        state: reloaded
    - name: "Add slayed to docker group"
      ansible.builtin.user:
        name: "{{ user }}"
        group: "docker"
        append: true
        shell: /bin/bash
