---
- name: Install essential packages
  hosts: all
  gather_facts: false
  remote_user: slayed
  become: true
  vars:
    user: "gnus"
    new_groups:
      - "kvm"
      - "libvirt"
    interface: "\tenp1s0:"
    interface_name: "\tinterfaces: [enp1s0]"
    ip_address: "\taddresses: [192.168.122.7/24]"
    mac_address: "\tmacaddress: 52:54:00:ea:b8:c8"
  tasks:
    - name: "Update apt-get repo and cache"
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: "Install essential packages"
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - virt-manager
          - libvirt-daemon-system
          - virtinst
          - libvirt-clients
          - bridge-utils
    - name: Reload service httpd, in all cases
      ansible.builtin.systemd:
        name: libvirtd.service
        enabled: true
        state: reloaded
    - name: Add user to libvirt & kvm
      ansible.builtin.user:
        name: "{{ user }}"
        groups: "{{ new_groups }}"
        append: true
      with_items:
        - "{{ new_groups }}"
