---
- name: Initial setup
  hosts: all
  gather_facts: false
  remote_user: gnus
  become: true
  vars:
    ssh_key_path: /home/gnus/repositories/blade/.ssh
    ssh_key_dest: /home/slayed/.ssh
    ssh_keys:
      - id_rsa
      - id_slayed
    ssh_keys_pub:
      - id_rsa.pub
      - id_slayed.pub
    user: slayed
  tasks:
    - name: "Add user slayed"
      ansible.builtin.user:
        name: slayed
        shell: /bin/bash
    - name: "Add slayed user to the sudoers"
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/slayed"
        content: "slayed  ALL=(ALL)  NOPASSWD: ALL"
        owner: root
        group: root
        mode: 0440
    - name: "Update apt-get repo and cache"
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: "Upgrade all apt packages"
      ansible.builtin.apt:
        upgrade: "dist"
        force_apt_get: true
    - name: "Creates directory"
      ansible.builtin.file:
        path: "/home/slayed/.ssh"
        state: "directory"
        mode: '0700'
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: "Copy private key to server"
      ansible.builtin.copy:
        src: "{{ ssh_key_path }}/{{ item }}"
        dest: "{{ ssh_key_dest }}"
        mode: '0600'
        owner: "{{ user }}"
        group: "{{ user }}"
      with_items:
        - "{{ ssh_keys }}"
    - name: "Copy public key to server"
      ansible.builtin.copy:
        src: "{{ ssh_key_path }}/{{ item }}"
        dest: "{{ ssh_key_dest }}"
        mode: '0644'
        owner: "{{ user }}"
        group: "{{ user }}"
      with_items:
        - "{{ ssh_keys_pub }}"
    - name: "Update SSH keys"
      ansible.posix.authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file',  '{{ ssh_key_path }}/{{ item }}') }}"
        state: present
      with_items:
        - "{{ ssh_keys_pub }}"
