---
- name: Initial setup
  hosts: all
  gather_facts: false
  remote_user: slayed
  become: true
  tasks:
    - name: "Disable Password Authentication"
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "'^PasswordAuthentication'"
        line: "PasswordAuthentication no"
        state: "present"
        backup: true
    - name: "Disable Root Login"
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "'^PermitRootLogin'"
        line: "PermitRootLogin no"
        state: "present"
        backup: true
      notify:
        - Restart ssh
  handlers:
    - name: "Restart ssh"
      ansible.builtin.service:
        name: "sshd"
        state: "restarted"
